import Providers from "@/lib/Providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApolloWrapper } from "./ApolloWrapper";
import Navbar from "./navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Navbar></Navbar>
          <ApolloWrapper>{children}</ApolloWrapper>
        </body>
      </html>
    </Providers>
  );
}
